import useApp from "../hooks/useApp.js";
import {useEffect} from "react";
import imagenIndex from "/src/assets/imagenIndex.png"
export default function Index() {

    const {setCurrentOption,
        setForm1,
        setForm2} = useApp()

    useEffect(()=>{
        setCurrentOption({})
        setForm1({})
        setForm2({})
    },[])

    return (
    <div className='rounded-xl text-transparent' style={{backgroundImage: `url(${imagenIndex})`,
                 backgroundRepeat: "no-repeat",
                 backgroundSize: "cover"
    }}>
        INICIO-NUESTROS SERVICIOSINICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOSINICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOSINICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOSINICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOSINICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOSINICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
        INICIO-NUESTROS SERVICIOS
    </div>
    )
}